### ISSUE TITLE
Cannot resolve method .getResources() and .getPackageName() 

### ISSUE THREAD

**Issue by GiuliCon** [OpenFTC/EasyOpenCV#25]
I don't know why, but Android Studio doesn't recognize .getResources() and .getPackageName() but this only happens to me, to my buddy, with the exact same project it works perfectly fine.
Here's the code:

```java
int cameraMonitorViewId = hardwareMap.appContext.getResources().getIdentifier("cameraMonitorViewId", "id", hardwareMap.appContext.getPackageName());
```

**Comment by Windwoes** [comment]
This is most certainly an issue with your Android Studio configuration, not with EasyOpenCV

**Comment by Windwoes** [comment]
Have you tried "Invalidate Caches and Restart" in Android Studio?
