### ISSUE TITLE
libOpenCvAndroid453.so is present in FIRST internal storage however checksum MD5 ... app crahses

### ISSUE THREAD

**Issue by anwarhamr** [OpenFTC/EasyOpenCV#34]
lib is corrupted is in the error title.
I've followed the example for installing your project but am getting the above error message and app crashes.  I'm on mac if that makes any different and used 'android file transfer' to move the file into the folder on the device.  Has anyone see this message?
I pulled the file from here OpenCV-Repackaged/doc/native_libs/armeabi-v7a/
I've tried the master and 453 branches and get the same error.

**Comment by anwarhamr** [comment]
The problem was the transfer probably due to me using a mac.  To fix on the phone, I added real wifi network, went to the file necessary to download and downloaded it on the phone.  Then moved the downloaded file to the FIRST folder on internal device storage.  Worked after that.

**Comment by Windwoes** [comment]
That's..... interesting. An alternative method would be to use `adb push libOpenCvAndroid453.so /sdcard/FIRST/`
