### ISSUE TITLE
Installation directions

### ISSUE THREAD

**Issue by Vector5233** [OpenFTC/EasyOpenCV#36]
Not an issue per se but a request for guidance.  When installing OpenCV under Android Studio, while using the Rev Control Hub rather than an Android Phone, what is the correct way to deposit the native library libOpenCvAndroid453.so into the FIRST folder?  The Rev device manager doesn't really expose the file structure of the Control Hub, so it's unclear where the library should go or how to get it there.  TIA!

**Comment by Windwoes** [comment]
Did you get this working?

**Comment by Vector5233** [comment]
Yes, we were able to access in File Explorer (Win 10).  Interestingly, the file manager im Android Studio would lock up when we tried to copy and paste the file into the Control Hub.  But Explorer worked, so on to the next thing!
