### ISSUE TITLE
Opencv internal camera can't  instantiated

### ISSUE THREAD

**Issue by ftc10015** [OpenFTC/EasyOpenCV#4]
![image](https://user-images.githubusercontent.com/56522224/71563820-48305280-2a53-11ea-8652-b9bd62f13198.png)

**Comment by FROGbots-4634** [comment]
You're using EasyOpenCV 1.3 or higher, but still using sample code from <= 1.2.

1.3 had an API change which changes how cameras are instantiated.

**Comment by ftc10015** [comment]
Thanks FROGbots, I changed to 1.2

**Comment by FROGbots-4634** [comment]
That's a *valid* solution, although you lose access to the new features provided by 1.3..... all you need to do is change it to be:

```java
phoneCam = OpenCvCameraFactory.getInstance().createInternalCamera(OpenCvInternalCamera.CameraDirection.BACK, cameraMonitorViewId);
```

**Comment by NoahAndrews** [comment]
In the future we should avoid having breaking changes in minor version updates.
