### ISSUE TITLE
MonitoringThread: The RC has not reported itself as alive for more than 10 seconds. Relaunching the RC.

### ISSUE THREAD

**Issue by wimos-ai** [OpenFTC/EasyOpenCV#43]
Today I came across an error with the EasyOpenCV library. It seems to cause the OpMode to not report itself as alive which leads to the shutdown of the app. I have attached a copy of the Robot Log Here:
[RobotLog.txt](https://github.com/OpenFTC/EasyOpenCV/files/8375489/RobotLog.txt)
 
As a temporary measure, I have removed all code that depends on EasyOpenCV and commented out the line:
implementation 'org.openftc:easyopencv:1.5.1'
in my TeamCode build. gradle which has fixed the problem. 

I am running on Rev Control Hub and the Driver Hub with SDK version 7.1

**Comment by Windwoes** [comment]
Can you please share your OpMode?

**Comment by wimos-ai** [comment]
We have written class wrappers for each subsystem on the robot with control methods for each so it is a lot of files for all the lines being executed in our OpMode.

**Comment by wimos-ai** [comment]
We switched out the cameras and that seemed to fix the issue
