### ISSUE TITLE
Explain how to close Camera Stream preview

### ISSUE THREAD

**Issue by WestsideRobotics** [OpenFTC/EasyOpenCV#45]
https://github.com/OpenFTC/EasyOpenCV/blob/master/doc/user_docs/camera_initialization_overview.md#using-the-driver-station-camera-preview-feature

In the above documentation section, I suggest mentioning how to exit the preview.  Something like this:

"Select `Camera Stream` again to close the preview and continue the OpMode."

**Comment by Windwoes** [comment]
Done, thank you :)
