### ISSUE TITLE
Constant Streaming

### ISSUE THREAD

**Issue by NikhilRao21** [OpenFTC/EasyOpenCV#49]
How do you get constant streaming to work on the camera?

**Comment by Windwoes** [comment]
What do you mean? Can you elaborate?

**Comment by SriramKalki** [comment]
He is probably asking if there is a way to view camera stream without having to "Tap to refresh"

**Comment by Windwoes** [comment]
Ah. Well the answer is that is an SDK limitation and there's no way around it. You can however connect the Control Hub to an HDMI monitor, or you can use `srccpy` to mirror the screen over ADB.

**Comment by NikhilRao21** [comment]
ok thanks
