### ISSUE TITLE
Missing Folder?

### ISSUE THREAD

**Issue by devinhunsberger** [OpenFTC/EasyOpenCV#5]
I tried a clean version of both the app master and the EasyOpenCV sdk's and I get an error where the script release-aar.gradle isn't a thing. It's apparently located in the ftc_app-master folder.

**Comment by FROGbots-4634** [comment]
You should not need to locally clone EasyOpenCV unless you want to work on developing EasyOpenCV itself. Otherwise, simply follow the installation instructions in the readme.
