### ISSUE TITLE
possible to setZoom for web camera?

### ISSUE THREAD

**Issue by wangxdflight** [OpenFTC/EasyOpenCV#52]
It seems that setZoom is only available for OpenCvInternalCamera, not OpenCvWebcam.
Possible to add the support for OpenCvWebcam?

Thanks.

**Comment by wangxdflight** [comment]
I played with PtzControl's getZoom, setZoom, but doesn't have effect on my Logitec C920 webcamera. Any help here? Or it is not feasible at all?

**Comment by Windwoes** [comment]
A C920 was my test camera when validating that functionality works, so I'm honestly not immediately sure what the issue might be.

**Comment by Windwoes** [comment]
Closing for now, feel free to re-open.
