### ISSUE TITLE
1.5.3 - duplicate class...

### ISSUE THREAD

**Issue by alan412** [OpenFTC/EasyOpenCV#59]
Perhaps this is something I just need to cleanup, but when I move OpenCV from 1.5.2 to 1.5.3 my FTC project won't build with a ton of duplicate class errors.  I tried clean project, grade sync, but that wasn't enough....

**Comment by Windwoes** [comment]
Is your workspace public anywhere?

**Comment by alan412** [comment]
Yes - https://github.com/ftc16072/PowerPlay22-23

**Comment by Windwoes** [comment]
Please update to AprilTag plugin v1.1.1. Previous versions incorrectly used `api` for their OpenCV dependency rather than `compileOnly`; this is causing two different versions of OpenCV-Repackaged to be pulled in.

**Comment by alan412** [comment]
That fixed it.  Thanks for the rapid response!!
