### ISSUE TITLE
onViewportTapped in StageSwitchingPipeline is never called

### ISSUE THREAD

**Issue by AusreisserSF** [OpenFTC/EasyOpenCV#67]
We're running under PowerPlay 8.1 using implementation 'org.openftc:easyopencv:1.6.2'. We noticed that our OpMode based on the example PipelineStageSwitchingExample (but using a webcam) never received a callback for onViewportTapped. The default Stage value appears in the viewport but a tap on the viewport produces an audible click but no change to the next Stage value. If we turn the camera and tap the viewport the image changes - as expected. We pulled a fresh copy of the example from the EasyOpenCV repo, changed the internal camera to a webcam, and tried again. But we got the same results - an image in the viewport but no change in Stage when the viewport is tapped.

**Comment by Windwoes** [comment]
`onViewportTapped` only works for the local preview on the RC phone. It does not work for the remote preview on the DS.
