### ISSUE TITLE
Cannot upload aar file to onbot java of FtcRobotController 9.0

### ISSUE THREAD

**Issue by junfengzh** [OpenFTC/EasyOpenCV#70]
It complains that the aar contains "classes that already exist in the robot controller".

EasyOpenCV version: 1.6.2
FtcRobotController version: 9.0
Hardware: Rev Control Hub

**Comment by Windwoes** [comment]
EOCV is now bundled with the SDK as of 8..2

**Comment by junfengzh** [comment]
Thanks for quick reply. Did we change the package path? I tried to build a Java file written for last season, and could not resolve classes like org.openftc.easyopencv.OpenCvWebcam.

**Comment by Windwoes** [comment]
Package path did not change.

**Comment by junfengzh** [comment]
Actually OpenCvWebcam is fine. It is really only org.openftc.easyopencv.OpenCvCameraFactory that is missing in SDK. When I commented out it, the rest of the code built successfully.

I tried to reinstall robot controller apk a couple of times on control hub and still get the same error.

**Comment by Windwoes** [comment]
I was able to reproduce this issue on a Nexus 5 with a clean install of the official 9.0 APK. I will look into it.

**Comment by ahoglund** [comment]
> EOCV is now bundled with the SDK as of 8.2

This fact should be made clearer on the README, so visitors won't try to add this to their FtcRobotController code

**Comment by Windwoes** [comment]
I updated the readme.
